export const UI_START_LOADING_ACTION = 'UI_START_LOADING_ACTION';
export const UI_STOP_LOADING_ACTION = 'UI_STOP_LOADING_ACTION';
export const UI_START_VALIDATING_ACTION = 'UI_START_VALIDATING_ACTION';
export const UI_STOP_VALIDATING_ACTION = 'UI_STOP_VALIDATING_ACTION';