const GAME_STATUS = {
    GAME_CREATED: 'CREATE GAME',
    GAME_JOINED: 'JOIN GAME',
    GAME_STARTED: 'START GAME',
    0: 'OPEN',
    1: 'STARTED',
    2: 'REVEAL',
    3: 'PAYOUT',
    JOINED_BET: 'JOIN BET',
    PLACED_BET: 'PLACE BET',
    WITHDRAWN_BET: 'WITHDRAW BET'
};

export default GAME_STATUS;
